<?php
declare(strict_types=1);

// Auto-generated by tools/generate-config.py
// Runtime-friendly config for CakePHP/plugin usage.

return [
    'Primitives' => [
        'glyphCount' => 68,
        'singleGlyphCount' => 68,
        'ligatureCount' => 0,
        'chars' => 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!,.:; ',
        'uppercase' => 'ABCDEFGHIJKLMNOPQRSTUVWXYZ',
        'lowercase' => 'abcdefghijklmnopqrstuvwxyz',
        'digits' => '0123456789',
        'punct' => '!,.:;',
        'other' => ' ',
        'codepoints' => [
            32,
            33,
            44,
            46,
            48,
            49,
            50,
            51,
            52,
            53,
            54,
            55,
            56,
            57,
            58,
            59,
            65,
            66,
            67,
            68,
            69,
            70,
            71,
            72,
            73,
            74,
            75,
            76,
            77,
            78,
            79,
            80,
            81,
            82,
            83,
            84,
            85,
            86,
            87,
            88,
            89,
            90,
            97,
            98,
            99,
            100,
            101,
            102,
            103,
            104,
            105,
            106,
            107,
            108,
            109,
            110,
            111,
            112,
            113,
            114,
            115,
            116,
            117,
            118,
            119,
            120,
            121,
            122,
        ],
        'unicodeRanges' => [
            [
                32,
                33,
            ],
            [
                44,
                44,
            ],
            [
                46,
                46,
            ],
            [
                48,
                59,
            ],
            [
                65,
                90,
            ],
            [
                97,
                122,
            ],
        ],
        'charToFilename' => [
            ' ' => 'character-u0020.svg',
            '!' => 'character-u0021.svg',
            ',' => 'character-u002c.svg',
            '.' => 'character-u002e.svg',
            '0' => 'character-u0030.svg',
            '1' => 'character-u0031.svg',
            '2' => 'character-u0032.svg',
            '3' => 'character-u0033.svg',
            '4' => 'character-u0034.svg',
            '5' => 'character-u0035.svg',
            '6' => 'character-u0036.svg',
            '7' => 'character-u0037.svg',
            '8' => 'character-u0038.svg',
            '9' => 'character-u0039.svg',
            ':' => 'character-u003a.svg',
            ';' => 'character-u003b.svg',
            'A' => 'character-u0041.svg',
            'B' => 'character-u0042.svg',
            'C' => 'character-u0043.svg',
            'D' => 'character-u0044.svg',
            'E' => 'character-u0045.svg',
            'F' => 'character-u0046.svg',
            'G' => 'character-u0047.svg',
            'H' => 'character-u0048.svg',
            'I' => 'character-u0049.svg',
            'J' => 'character-u004a.svg',
            'K' => 'character-u004b.svg',
            'L' => 'character-u004c.svg',
            'M' => 'character-u004d.svg',
            'N' => 'character-u004e.svg',
            'O' => 'character-u004f.svg',
            'P' => 'character-u0050.svg',
            'Q' => 'character-u0051.svg',
            'R' => 'character-u0052.svg',
            'S' => 'character-u0053.svg',
            'T' => 'character-u0054.svg',
            'U' => 'character-u0055.svg',
            'V' => 'character-u0056.svg',
            'W' => 'character-u0057.svg',
            'X' => 'character-u0058.svg',
            'Y' => 'character-u0059.svg',
            'Z' => 'character-u005a.svg',
            'a' => 'character-u0061.svg',
            'b' => 'character-u0062.svg',
            'c' => 'character-u0063.svg',
            'd' => 'character-u0064.svg',
            'e' => 'character-u0065.svg',
            'f' => 'character-u0066.svg',
            'g' => 'character-u0067.svg',
            'h' => 'character-u0068.svg',
            'i' => 'character-u0069.svg',
            'j' => 'character-u006a.svg',
            'k' => 'character-u006b.svg',
            'l' => 'character-u006c.svg',
            'm' => 'character-u006d.svg',
            'n' => 'character-u006e.svg',
            'o' => 'character-u006f.svg',
            'p' => 'character-u0070.svg',
            'q' => 'character-u0071.svg',
            'r' => 'character-u0072.svg',
            's' => 'character-u0073.svg',
            't' => 'character-u0074.svg',
            'u' => 'character-u0075.svg',
            'v' => 'character-u0076.svg',
            'w' => 'character-u0077.svg',
            'x' => 'character-u0078.svg',
            'y' => 'character-u0079.svg',
            'z' => 'character-u007a.svg',
        ],
        'charToUnicode' => [
            ' ' => 'U+0020',
            '!' => 'U+0021',
            ',' => 'U+002C',
            '.' => 'U+002E',
            '0' => 'U+0030',
            '1' => 'U+0031',
            '2' => 'U+0032',
            '3' => 'U+0033',
            '4' => 'U+0034',
            '5' => 'U+0035',
            '6' => 'U+0036',
            '7' => 'U+0037',
            '8' => 'U+0038',
            '9' => 'U+0039',
            ':' => 'U+003A',
            ';' => 'U+003B',
            'A' => 'U+0041',
            'B' => 'U+0042',
            'C' => 'U+0043',
            'D' => 'U+0044',
            'E' => 'U+0045',
            'F' => 'U+0046',
            'G' => 'U+0047',
            'H' => 'U+0048',
            'I' => 'U+0049',
            'J' => 'U+004A',
            'K' => 'U+004B',
            'L' => 'U+004C',
            'M' => 'U+004D',
            'N' => 'U+004E',
            'O' => 'U+004F',
            'P' => 'U+0050',
            'Q' => 'U+0051',
            'R' => 'U+0052',
            'S' => 'U+0053',
            'T' => 'U+0054',
            'U' => 'U+0055',
            'V' => 'U+0056',
            'W' => 'U+0057',
            'X' => 'U+0058',
            'Y' => 'U+0059',
            'Z' => 'U+005A',
            'a' => 'U+0061',
            'b' => 'U+0062',
            'c' => 'U+0063',
            'd' => 'U+0064',
            'e' => 'U+0065',
            'f' => 'U+0066',
            'g' => 'U+0067',
            'h' => 'U+0068',
            'i' => 'U+0069',
            'j' => 'U+006A',
            'k' => 'U+006B',
            'l' => 'U+006C',
            'm' => 'U+006D',
            'n' => 'U+006E',
            'o' => 'U+006F',
            'p' => 'U+0070',
            'q' => 'U+0071',
            'r' => 'U+0072',
            's' => 'U+0073',
            't' => 'U+0074',
            'u' => 'U+0075',
            'v' => 'U+0076',
            'w' => 'U+0077',
            'x' => 'U+0078',
            'y' => 'U+0079',
            'z' => 'U+007A',
        ],
        'ligatureKeys' => [],
        'ligatures' => [],
        'svgMap' => [
            ' ' => 'character-u0020.svg',
            '!' => 'character-u0021.svg',
            ',' => 'character-u002c.svg',
            '.' => 'character-u002e.svg',
            '0' => 'character-u0030.svg',
            '1' => 'character-u0031.svg',
            '2' => 'character-u0032.svg',
            '3' => 'character-u0033.svg',
            '4' => 'character-u0034.svg',
            '5' => 'character-u0035.svg',
            '6' => 'character-u0036.svg',
            '7' => 'character-u0037.svg',
            '8' => 'character-u0038.svg',
            '9' => 'character-u0039.svg',
            ':' => 'character-u003a.svg',
            ';' => 'character-u003b.svg',
            'A' => 'character-u0041.svg',
            'B' => 'character-u0042.svg',
            'C' => 'character-u0043.svg',
            'D' => 'character-u0044.svg',
            'E' => 'character-u0045.svg',
            'F' => 'character-u0046.svg',
            'G' => 'character-u0047.svg',
            'H' => 'character-u0048.svg',
            'I' => 'character-u0049.svg',
            'J' => 'character-u004a.svg',
            'K' => 'character-u004b.svg',
            'L' => 'character-u004c.svg',
            'M' => 'character-u004d.svg',
            'N' => 'character-u004e.svg',
            'O' => 'character-u004f.svg',
            'P' => 'character-u0050.svg',
            'Q' => 'character-u0051.svg',
            'R' => 'character-u0052.svg',
            'S' => 'character-u0053.svg',
            'T' => 'character-u0054.svg',
            'U' => 'character-u0055.svg',
            'V' => 'character-u0056.svg',
            'W' => 'character-u0057.svg',
            'X' => 'character-u0058.svg',
            'Y' => 'character-u0059.svg',
            'Z' => 'character-u005a.svg',
            'a' => 'character-u0061.svg',
            'b' => 'character-u0062.svg',
            'c' => 'character-u0063.svg',
            'd' => 'character-u0064.svg',
            'e' => 'character-u0065.svg',
            'f' => 'character-u0066.svg',
            'g' => 'character-u0067.svg',
            'h' => 'character-u0068.svg',
            'i' => 'character-u0069.svg',
            'j' => 'character-u006a.svg',
            'k' => 'character-u006b.svg',
            'l' => 'character-u006c.svg',
            'm' => 'character-u006d.svg',
            'n' => 'character-u006e.svg',
            'o' => 'character-u006f.svg',
            'p' => 'character-u0070.svg',
            'q' => 'character-u0071.svg',
            'r' => 'character-u0072.svg',
            's' => 'character-u0073.svg',
            't' => 'character-u0074.svg',
            'u' => 'character-u0075.svg',
            'v' => 'character-u0076.svg',
            'w' => 'character-u0077.svg',
            'x' => 'character-u0078.svg',
            'y' => 'character-u0079.svg',
            'z' => 'character-u007a.svg',
        ],
        'glyphs' => [
            ' ' => [
                'key' => ' ',
                'filename' => 'character-u0020.svg',
                'isLigature' => false,
                'length' => 1,
                'chars' => [
                    ' ',
                ],
                'codepoints' => [
                    32,
                ],
                'unicode' => [
                    'U+0020',
                ],
            ],
            '!' => [
                'key' => '!',
                'filename' => 'character-u0021.svg',
                'isLigature' => false,
                'length' => 1,
                'chars' => [
                    '!',
                ],
                'codepoints' => [
                    33,
                ],
                'unicode' => [
                    'U+0021',
                ],
            ],
            ',' => [
                'key' => ',',
                'filename' => 'character-u002c.svg',
                'isLigature' => false,
                'length' => 1,
                'chars' => [
                    ',',
                ],
                'codepoints' => [
                    44,
                ],
                'unicode' => [
                    'U+002C',
                ],
            ],
            '.' => [
                'key' => '.',
                'filename' => 'character-u002e.svg',
                'isLigature' => false,
                'length' => 1,
                'chars' => [
                    '.',
                ],
                'codepoints' => [
                    46,
                ],
                'unicode' => [
                    'U+002E',
                ],
            ],
            '0' => [
                'key' => '0',
                'filename' => 'character-u0030.svg',
                'isLigature' => false,
                'length' => 1,
                'chars' => [
                    '0',
                ],
                'codepoints' => [
                    48,
                ],
                'unicode' => [
                    'U+0030',
                ],
            ],
            '1' => [
                'key' => '1',
                'filename' => 'character-u0031.svg',
                'isLigature' => false,
                'length' => 1,
                'chars' => [
                    '1',
                ],
                'codepoints' => [
                    49,
                ],
                'unicode' => [
                    'U+0031',
                ],
            ],
            '2' => [
                'key' => '2',
                'filename' => 'character-u0032.svg',
                'isLigature' => false,
                'length' => 1,
                'chars' => [
                    '2',
                ],
                'codepoints' => [
                    50,
                ],
                'unicode' => [
                    'U+0032',
                ],
            ],
            '3' => [
                'key' => '3',
                'filename' => 'character-u0033.svg',
                'isLigature' => false,
                'length' => 1,
                'chars' => [
                    '3',
                ],
                'codepoints' => [
                    51,
                ],
                'unicode' => [
                    'U+0033',
                ],
            ],
            '4' => [
                'key' => '4',
                'filename' => 'character-u0034.svg',
                'isLigature' => false,
                'length' => 1,
                'chars' => [
                    '4',
                ],
                'codepoints' => [
                    52,
                ],
                'unicode' => [
                    'U+0034',
                ],
            ],
            '5' => [
                'key' => '5',
                'filename' => 'character-u0035.svg',
                'isLigature' => false,
                'length' => 1,
                'chars' => [
                    '5',
                ],
                'codepoints' => [
                    53,
                ],
                'unicode' => [
                    'U+0035',
                ],
            ],
            '6' => [
                'key' => '6',
                'filename' => 'character-u0036.svg',
                'isLigature' => false,
                'length' => 1,
                'chars' => [
                    '6',
                ],
                'codepoints' => [
                    54,
                ],
                'unicode' => [
                    'U+0036',
                ],
            ],
            '7' => [
                'key' => '7',
                'filename' => 'character-u0037.svg',
                'isLigature' => false,
                'length' => 1,
                'chars' => [
                    '7',
                ],
                'codepoints' => [
                    55,
                ],
                'unicode' => [
                    'U+0037',
                ],
            ],
            '8' => [
                'key' => '8',
                'filename' => 'character-u0038.svg',
                'isLigature' => false,
                'length' => 1,
                'chars' => [
                    '8',
                ],
                'codepoints' => [
                    56,
                ],
                'unicode' => [
                    'U+0038',
                ],
            ],
            '9' => [
                'key' => '9',
                'filename' => 'character-u0039.svg',
                'isLigature' => false,
                'length' => 1,
                'chars' => [
                    '9',
                ],
                'codepoints' => [
                    57,
                ],
                'unicode' => [
                    'U+0039',
                ],
            ],
            ':' => [
                'key' => ':',
                'filename' => 'character-u003a.svg',
                'isLigature' => false,
                'length' => 1,
                'chars' => [
                    ':',
                ],
                'codepoints' => [
                    58,
                ],
                'unicode' => [
                    'U+003A',
                ],
            ],
            ';' => [
                'key' => ';',
                'filename' => 'character-u003b.svg',
                'isLigature' => false,
                'length' => 1,
                'chars' => [
                    ';',
                ],
                'codepoints' => [
                    59,
                ],
                'unicode' => [
                    'U+003B',
                ],
            ],
            'A' => [
                'key' => 'A',
                'filename' => 'character-u0041.svg',
                'isLigature' => false,
                'length' => 1,
                'chars' => [
                    'A',
                ],
                'codepoints' => [
                    65,
                ],
                'unicode' => [
                    'U+0041',
                ],
            ],
            'B' => [
                'key' => 'B',
                'filename' => 'character-u0042.svg',
                'isLigature' => false,
                'length' => 1,
                'chars' => [
                    'B',
                ],
                'codepoints' => [
                    66,
                ],
                'unicode' => [
                    'U+0042',
                ],
            ],
            'C' => [
                'key' => 'C',
                'filename' => 'character-u0043.svg',
                'isLigature' => false,
                'length' => 1,
                'chars' => [
                    'C',
                ],
                'codepoints' => [
                    67,
                ],
                'unicode' => [
                    'U+0043',
                ],
            ],
            'D' => [
                'key' => 'D',
                'filename' => 'character-u0044.svg',
                'isLigature' => false,
                'length' => 1,
                'chars' => [
                    'D',
                ],
                'codepoints' => [
                    68,
                ],
                'unicode' => [
                    'U+0044',
                ],
            ],
            'E' => [
                'key' => 'E',
                'filename' => 'character-u0045.svg',
                'isLigature' => false,
                'length' => 1,
                'chars' => [
                    'E',
                ],
                'codepoints' => [
                    69,
                ],
                'unicode' => [
                    'U+0045',
                ],
            ],
            'F' => [
                'key' => 'F',
                'filename' => 'character-u0046.svg',
                'isLigature' => false,
                'length' => 1,
                'chars' => [
                    'F',
                ],
                'codepoints' => [
                    70,
                ],
                'unicode' => [
                    'U+0046',
                ],
            ],
            'G' => [
                'key' => 'G',
                'filename' => 'character-u0047.svg',
                'isLigature' => false,
                'length' => 1,
                'chars' => [
                    'G',
                ],
                'codepoints' => [
                    71,
                ],
                'unicode' => [
                    'U+0047',
                ],
            ],
            'H' => [
                'key' => 'H',
                'filename' => 'character-u0048.svg',
                'isLigature' => false,
                'length' => 1,
                'chars' => [
                    'H',
                ],
                'codepoints' => [
                    72,
                ],
                'unicode' => [
                    'U+0048',
                ],
            ],
            'I' => [
                'key' => 'I',
                'filename' => 'character-u0049.svg',
                'isLigature' => false,
                'length' => 1,
                'chars' => [
                    'I',
                ],
                'codepoints' => [
                    73,
                ],
                'unicode' => [
                    'U+0049',
                ],
            ],
            'J' => [
                'key' => 'J',
                'filename' => 'character-u004a.svg',
                'isLigature' => false,
                'length' => 1,
                'chars' => [
                    'J',
                ],
                'codepoints' => [
                    74,
                ],
                'unicode' => [
                    'U+004A',
                ],
            ],
            'K' => [
                'key' => 'K',
                'filename' => 'character-u004b.svg',
                'isLigature' => false,
                'length' => 1,
                'chars' => [
                    'K',
                ],
                'codepoints' => [
                    75,
                ],
                'unicode' => [
                    'U+004B',
                ],
            ],
            'L' => [
                'key' => 'L',
                'filename' => 'character-u004c.svg',
                'isLigature' => false,
                'length' => 1,
                'chars' => [
                    'L',
                ],
                'codepoints' => [
                    76,
                ],
                'unicode' => [
                    'U+004C',
                ],
            ],
            'M' => [
                'key' => 'M',
                'filename' => 'character-u004d.svg',
                'isLigature' => false,
                'length' => 1,
                'chars' => [
                    'M',
                ],
                'codepoints' => [
                    77,
                ],
                'unicode' => [
                    'U+004D',
                ],
            ],
            'N' => [
                'key' => 'N',
                'filename' => 'character-u004e.svg',
                'isLigature' => false,
                'length' => 1,
                'chars' => [
                    'N',
                ],
                'codepoints' => [
                    78,
                ],
                'unicode' => [
                    'U+004E',
                ],
            ],
            'O' => [
                'key' => 'O',
                'filename' => 'character-u004f.svg',
                'isLigature' => false,
                'length' => 1,
                'chars' => [
                    'O',
                ],
                'codepoints' => [
                    79,
                ],
                'unicode' => [
                    'U+004F',
                ],
            ],
            'P' => [
                'key' => 'P',
                'filename' => 'character-u0050.svg',
                'isLigature' => false,
                'length' => 1,
                'chars' => [
                    'P',
                ],
                'codepoints' => [
                    80,
                ],
                'unicode' => [
                    'U+0050',
                ],
            ],
            'Q' => [
                'key' => 'Q',
                'filename' => 'character-u0051.svg',
                'isLigature' => false,
                'length' => 1,
                'chars' => [
                    'Q',
                ],
                'codepoints' => [
                    81,
                ],
                'unicode' => [
                    'U+0051',
                ],
            ],
            'R' => [
                'key' => 'R',
                'filename' => 'character-u0052.svg',
                'isLigature' => false,
                'length' => 1,
                'chars' => [
                    'R',
                ],
                'codepoints' => [
                    82,
                ],
                'unicode' => [
                    'U+0052',
                ],
            ],
            'S' => [
                'key' => 'S',
                'filename' => 'character-u0053.svg',
                'isLigature' => false,
                'length' => 1,
                'chars' => [
                    'S',
                ],
                'codepoints' => [
                    83,
                ],
                'unicode' => [
                    'U+0053',
                ],
            ],
            'T' => [
                'key' => 'T',
                'filename' => 'character-u0054.svg',
                'isLigature' => false,
                'length' => 1,
                'chars' => [
                    'T',
                ],
                'codepoints' => [
                    84,
                ],
                'unicode' => [
                    'U+0054',
                ],
            ],
            'U' => [
                'key' => 'U',
                'filename' => 'character-u0055.svg',
                'isLigature' => false,
                'length' => 1,
                'chars' => [
                    'U',
                ],
                'codepoints' => [
                    85,
                ],
                'unicode' => [
                    'U+0055',
                ],
            ],
            'V' => [
                'key' => 'V',
                'filename' => 'character-u0056.svg',
                'isLigature' => false,
                'length' => 1,
                'chars' => [
                    'V',
                ],
                'codepoints' => [
                    86,
                ],
                'unicode' => [
                    'U+0056',
                ],
            ],
            'W' => [
                'key' => 'W',
                'filename' => 'character-u0057.svg',
                'isLigature' => false,
                'length' => 1,
                'chars' => [
                    'W',
                ],
                'codepoints' => [
                    87,
                ],
                'unicode' => [
                    'U+0057',
                ],
            ],
            'X' => [
                'key' => 'X',
                'filename' => 'character-u0058.svg',
                'isLigature' => false,
                'length' => 1,
                'chars' => [
                    'X',
                ],
                'codepoints' => [
                    88,
                ],
                'unicode' => [
                    'U+0058',
                ],
            ],
            'Y' => [
                'key' => 'Y',
                'filename' => 'character-u0059.svg',
                'isLigature' => false,
                'length' => 1,
                'chars' => [
                    'Y',
                ],
                'codepoints' => [
                    89,
                ],
                'unicode' => [
                    'U+0059',
                ],
            ],
            'Z' => [
                'key' => 'Z',
                'filename' => 'character-u005a.svg',
                'isLigature' => false,
                'length' => 1,
                'chars' => [
                    'Z',
                ],
                'codepoints' => [
                    90,
                ],
                'unicode' => [
                    'U+005A',
                ],
            ],
            'a' => [
                'key' => 'a',
                'filename' => 'character-u0061.svg',
                'isLigature' => false,
                'length' => 1,
                'chars' => [
                    'a',
                ],
                'codepoints' => [
                    97,
                ],
                'unicode' => [
                    'U+0061',
                ],
            ],
            'b' => [
                'key' => 'b',
                'filename' => 'character-u0062.svg',
                'isLigature' => false,
                'length' => 1,
                'chars' => [
                    'b',
                ],
                'codepoints' => [
                    98,
                ],
                'unicode' => [
                    'U+0062',
                ],
            ],
            'c' => [
                'key' => 'c',
                'filename' => 'character-u0063.svg',
                'isLigature' => false,
                'length' => 1,
                'chars' => [
                    'c',
                ],
                'codepoints' => [
                    99,
                ],
                'unicode' => [
                    'U+0063',
                ],
            ],
            'd' => [
                'key' => 'd',
                'filename' => 'character-u0064.svg',
                'isLigature' => false,
                'length' => 1,
                'chars' => [
                    'd',
                ],
                'codepoints' => [
                    100,
                ],
                'unicode' => [
                    'U+0064',
                ],
            ],
            'e' => [
                'key' => 'e',
                'filename' => 'character-u0065.svg',
                'isLigature' => false,
                'length' => 1,
                'chars' => [
                    'e',
                ],
                'codepoints' => [
                    101,
                ],
                'unicode' => [
                    'U+0065',
                ],
            ],
            'f' => [
                'key' => 'f',
                'filename' => 'character-u0066.svg',
                'isLigature' => false,
                'length' => 1,
                'chars' => [
                    'f',
                ],
                'codepoints' => [
                    102,
                ],
                'unicode' => [
                    'U+0066',
                ],
            ],
            'g' => [
                'key' => 'g',
                'filename' => 'character-u0067.svg',
                'isLigature' => false,
                'length' => 1,
                'chars' => [
                    'g',
                ],
                'codepoints' => [
                    103,
                ],
                'unicode' => [
                    'U+0067',
                ],
            ],
            'h' => [
                'key' => 'h',
                'filename' => 'character-u0068.svg',
                'isLigature' => false,
                'length' => 1,
                'chars' => [
                    'h',
                ],
                'codepoints' => [
                    104,
                ],
                'unicode' => [
                    'U+0068',
                ],
            ],
            'i' => [
                'key' => 'i',
                'filename' => 'character-u0069.svg',
                'isLigature' => false,
                'length' => 1,
                'chars' => [
                    'i',
                ],
                'codepoints' => [
                    105,
                ],
                'unicode' => [
                    'U+0069',
                ],
            ],
            'j' => [
                'key' => 'j',
                'filename' => 'character-u006a.svg',
                'isLigature' => false,
                'length' => 1,
                'chars' => [
                    'j',
                ],
                'codepoints' => [
                    106,
                ],
                'unicode' => [
                    'U+006A',
                ],
            ],
            'k' => [
                'key' => 'k',
                'filename' => 'character-u006b.svg',
                'isLigature' => false,
                'length' => 1,
                'chars' => [
                    'k',
                ],
                'codepoints' => [
                    107,
                ],
                'unicode' => [
                    'U+006B',
                ],
            ],
            'l' => [
                'key' => 'l',
                'filename' => 'character-u006c.svg',
                'isLigature' => false,
                'length' => 1,
                'chars' => [
                    'l',
                ],
                'codepoints' => [
                    108,
                ],
                'unicode' => [
                    'U+006C',
                ],
            ],
            'm' => [
                'key' => 'm',
                'filename' => 'character-u006d.svg',
                'isLigature' => false,
                'length' => 1,
                'chars' => [
                    'm',
                ],
                'codepoints' => [
                    109,
                ],
                'unicode' => [
                    'U+006D',
                ],
            ],
            'n' => [
                'key' => 'n',
                'filename' => 'character-u006e.svg',
                'isLigature' => false,
                'length' => 1,
                'chars' => [
                    'n',
                ],
                'codepoints' => [
                    110,
                ],
                'unicode' => [
                    'U+006E',
                ],
            ],
            'o' => [
                'key' => 'o',
                'filename' => 'character-u006f.svg',
                'isLigature' => false,
                'length' => 1,
                'chars' => [
                    'o',
                ],
                'codepoints' => [
                    111,
                ],
                'unicode' => [
                    'U+006F',
                ],
            ],
            'p' => [
                'key' => 'p',
                'filename' => 'character-u0070.svg',
                'isLigature' => false,
                'length' => 1,
                'chars' => [
                    'p',
                ],
                'codepoints' => [
                    112,
                ],
                'unicode' => [
                    'U+0070',
                ],
            ],
            'q' => [
                'key' => 'q',
                'filename' => 'character-u0071.svg',
                'isLigature' => false,
                'length' => 1,
                'chars' => [
                    'q',
                ],
                'codepoints' => [
                    113,
                ],
                'unicode' => [
                    'U+0071',
                ],
            ],
            'r' => [
                'key' => 'r',
                'filename' => 'character-u0072.svg',
                'isLigature' => false,
                'length' => 1,
                'chars' => [
                    'r',
                ],
                'codepoints' => [
                    114,
                ],
                'unicode' => [
                    'U+0072',
                ],
            ],
            's' => [
                'key' => 's',
                'filename' => 'character-u0073.svg',
                'isLigature' => false,
                'length' => 1,
                'chars' => [
                    's',
                ],
                'codepoints' => [
                    115,
                ],
                'unicode' => [
                    'U+0073',
                ],
            ],
            't' => [
                'key' => 't',
                'filename' => 'character-u0074.svg',
                'isLigature' => false,
                'length' => 1,
                'chars' => [
                    't',
                ],
                'codepoints' => [
                    116,
                ],
                'unicode' => [
                    'U+0074',
                ],
            ],
            'u' => [
                'key' => 'u',
                'filename' => 'character-u0075.svg',
                'isLigature' => false,
                'length' => 1,
                'chars' => [
                    'u',
                ],
                'codepoints' => [
                    117,
                ],
                'unicode' => [
                    'U+0075',
                ],
            ],
            'v' => [
                'key' => 'v',
                'filename' => 'character-u0076.svg',
                'isLigature' => false,
                'length' => 1,
                'chars' => [
                    'v',
                ],
                'codepoints' => [
                    118,
                ],
                'unicode' => [
                    'U+0076',
                ],
            ],
            'w' => [
                'key' => 'w',
                'filename' => 'character-u0077.svg',
                'isLigature' => false,
                'length' => 1,
                'chars' => [
                    'w',
                ],
                'codepoints' => [
                    119,
                ],
                'unicode' => [
                    'U+0077',
                ],
            ],
            'x' => [
                'key' => 'x',
                'filename' => 'character-u0078.svg',
                'isLigature' => false,
                'length' => 1,
                'chars' => [
                    'x',
                ],
                'codepoints' => [
                    120,
                ],
                'unicode' => [
                    'U+0078',
                ],
            ],
            'y' => [
                'key' => 'y',
                'filename' => 'character-u0079.svg',
                'isLigature' => false,
                'length' => 1,
                'chars' => [
                    'y',
                ],
                'codepoints' => [
                    121,
                ],
                'unicode' => [
                    'U+0079',
                ],
            ],
            'z' => [
                'key' => 'z',
                'filename' => 'character-u007a.svg',
                'isLigature' => false,
                'length' => 1,
                'chars' => [
                    'z',
                ],
                'codepoints' => [
                    122,
                ],
                'unicode' => [
                    'U+007A',
                ],
            ],
        ],
        'hasUppercase' => true,
        'hasLowercase' => true,
        'hasDigits' => true,
        'hasPunct' => true,
    ],
];
