#!/usr/bin/env python3
"""
tools/generate-fonts.py

Build a COLR/CPAL color TrueType font from glyph definitions in:
  data/glyphs.py   (auto-generated by tools/generate-data.py)

Outputs (all to ../dist/fonts/):
  dist/fonts/primitives.ttf
  dist/fonts/primitives.woff
  dist/fonts/primitives.woff2   (if woff2/brotli support is available)
  dist/fonts/primitives.css      (copied from src/style/main.css)

Also:
- Adds a monochrome alternate for every mapped single-codepoint glyph via OpenType feature ss01.
  (ss01 swaps UXXXX -> UXXXX.mono; mono glyphs have NO COLR mapping.)

Notes:
- Colors are baked into the font.
- Palette index per tile remains deterministic (CRC32), so CSS palette overrides still work well.
- Ligatures/multi-codepoint entries in GLYPH_DATA are ignored for now (no cmap/GSUB liga here).
"""

from __future__ import annotations

import math
import random
import sys
import zlib
import importlib.util
from pathlib import Path
from typing import Dict, List, Optional, Tuple
from collections import OrderedDict
import types

from fontTools.colorLib.builder import buildCOLR, buildCPAL
from fontTools.feaLib.builder import addOpenTypeFeaturesFromString
from fontTools.fontBuilder import FontBuilder
from fontTools.pens.cu2quPen import Cu2QuPen
from fontTools.pens.ttGlyphPen import TTGlyphPen
from fontTools.ttLib import TTFont
from fontTools.ttLib.tables import otTables as ot


# -----------------------------
# Font / layout config
# -----------------------------
FAMILY_NAME = "Primitives"
STYLE_NAME = "Regular"

UPM = 1000
ASCENT = 700
DESCENT = 300  # positive; written as negative in headers

# Keep existing "5x9 in 600 units" layout; narrower glyphs simply occupy less.
ADVANCE_WIDTH = 600

# Font-unit cell (matches earlier generator)
CELL = 100
LEFT = 50
TOP = 600

PALETTE_SIZE = 256
PALETTE_SEED = 42

OUT_BASENAME = "primitives"


# -----------------------------
# Load data/glyphs.py
# -----------------------------
def _load_glyphs_module(root_dir: Path):
    glyphs_py = root_dir / "data" / "glyphs.py"
    if not glyphs_py.exists():
        raise SystemExit(f"Missing {glyphs_py}. Run tools/generate-data.py first.")

    # Execute the file in a controlled namespace that provides OrderedDict
    ns = {
        "__file__": str(glyphs_py),
        "__name__": "glyphs_data",
        "OrderedDict": OrderedDict,
    }
    code = glyphs_py.read_text(encoding="utf-8")
    exec(compile(code, str(glyphs_py), "exec"), ns, ns)

    mod = types.SimpleNamespace(**ns)
    return mod


def _gname_from_codepoint_hex(cp_hex: str) -> str:
    # cp_hex like "0041" from data/glyphs.py
    cp_hex = cp_hex.strip()
    return f"U{cp_hex.upper().zfill(4)}" if len(cp_hex) <= 4 else f"U{cp_hex.upper()}"


# -----------------------------
# Primitive outlines (glyf)
# IMPORTANT: p4/p5 are defined so that p4 is "left half (flat RIGHT, bulge LEFT)"
# and p5 is "right half (flat LEFT, bulge RIGHT)" – matching the project’s usage.
# -----------------------------
def draw_rect(pen: TTGlyphPen, x0: float, y0: float, x1: float, y1: float) -> None:
    pen.moveTo((x0, y0))
    pen.lineTo((x1, y0))
    pen.lineTo((x1, y1))
    pen.lineTo((x0, y1))
    pen.closePath()


def cubic_arc_to(pen, cx: float, cy: float, r: float, a0: float, a1: float) -> None:
    da = a1 - a0
    if da == 0:
        return
    nseg = max(1, int(math.ceil(abs(da) / (math.pi / 2))))
    step = da / nseg

    for i in range(nseg):
        t0 = a0 + i * step
        t1 = t0 + step

        x0 = cx + r * math.cos(t0)
        y0 = cy + r * math.sin(t0)
        x3 = cx + r * math.cos(t1)
        y3 = cy + r * math.sin(t1)

        k = 4.0 / 3.0 * math.tan((t1 - t0) / 4.0)

        dx0 = -r * math.sin(t0)
        dy0 = r * math.cos(t0)
        dx1 = -r * math.sin(t1)
        dy1 = r * math.cos(t1)

        x1 = x0 + k * dx0
        y1 = y0 + k * dy0
        x2 = x3 - k * dx1
        y2 = y3 - k * dy1

        pen.curveTo((x1, y1), (x2, y2), (x3, y3))


def build_primitive_glyph(pid: int):
    ttpen = TTGlyphPen(None)
    pen = Cu2QuPen(ttpen, max_err=1.0, reverse_direction=False)

    s = float(CELL)
    r = s / 2.0

    if pid == 0:
        draw_rect(pen, 0, 0, s, s)

    elif pid == 1:
        pen.moveTo((s, r))
        cubic_arc_to(pen, r, r, r, 0.0, 2.0 * math.pi)
        pen.closePath()

    elif pid == 2:
        # bottom half: flat bottom, bulge up
        pen.moveTo((0, 0))
        pen.lineTo((s, 0))
        cubic_arc_to(pen, r, 0.0, r, 0.0, math.pi)
        pen.closePath()

    elif pid == 3:
        # top half: flat top, bulge down
        pen.moveTo((0, s))
        pen.lineTo((s, s))
        cubic_arc_to(pen, r, s, r, 0.0, -math.pi)
        pen.closePath()

    elif pid == 4:
        # LEFT half (flat RIGHT), bulge LEFT in the cell => occupies right side of cell
        pen.moveTo((s, 0))
        pen.lineTo((s, s))
        cubic_arc_to(pen, s, r, r, math.pi / 2.0, 3.0 * math.pi / 2.0)
        pen.closePath()

    elif pid == 5:
        # RIGHT half (flat LEFT), bulge RIGHT in the cell => occupies left side of cell
        pen.moveTo((0, 0))
        pen.lineTo((0, s))
        cubic_arc_to(pen, 0.0, r, r, math.pi / 2.0, -math.pi / 2.0)
        pen.closePath()

    elif pid == 6:
        # quarter: top-right
        pen.moveTo((0, s))
        pen.lineTo((s, s))
        pen.lineTo((s, 0))
        cubic_arc_to(pen, s, s, s, 3.0 * math.pi / 2.0, math.pi)
        pen.closePath()

    elif pid == 7:
        # quarter: bottom-right
        pen.moveTo((s, s))
        pen.lineTo((s, 0))
        pen.lineTo((0, 0))
        cubic_arc_to(pen, s, 0.0, s, math.pi, math.pi / 2.0)
        pen.closePath()

    elif pid == 8:
        # quarter: bottom-left
        pen.moveTo((s, 0))
        pen.lineTo((0, 0))
        pen.lineTo((0, s))
        cubic_arc_to(pen, 0.0, 0.0, s, math.pi / 2.0, 0.0)
        pen.closePath()

    elif pid == 9:
        # quarter: top-left
        pen.moveTo((0, 0))
        pen.lineTo((0, s))
        pen.lineTo((s, s))
        cubic_arc_to(pen, 0.0, s, s, 0.0, -math.pi / 2.0)
        pen.closePath()

    else:
        draw_rect(pen, 0, 0, s, s)

    return ttpen.glyph()


def build_notdef():
    pen = TTGlyphPen(None)
    draw_rect(pen, 50, -250, 550, 650)
    draw_rect(pen, 100, -200, 500, 600)
    return pen.glyph()


# -----------------------------
# Glyph builders from tiles
# -----------------------------
Tile = Tuple[int, int, int]  # (col, row, primitive_id)


def _tiles_from_record(rec) -> List[Tile]:
    tiles = rec.get("tiles") or []
    out: List[Tile] = []
    for t in tiles:
        out.append((int(t["x"]), int(t["y"]), int(t["primitive"])))
    return out


def build_fallback_from_tiles(tiles: List[Tile]):
    # Simple bitmap fallback: fill each occupied tile as a square.
    pen = TTGlyphPen(None)
    for col, row, _pid in tiles:
        x0 = LEFT + col * CELL
        y1 = TOP - row * CELL
        y0 = y1 - CELL
        draw_rect(pen, x0, y0, x0 + CELL, y1)
    return pen.glyph()


def build_mono_composite_glyph(tiles: List[Tile], glyphset):
    # Composite of p0..p9 components; needs glyphset for membership checks.
    pen = TTGlyphPen(glyphset)
    for col, row, pid in tiles:
        dx = LEFT + col * CELL
        dy = TOP - (row + 1) * CELL
        pen.addComponent(f"p{pid}", (1, 0, 0, 1, dx, dy))
    return pen.glyph()


def palette_index_for(glyph_name: str, col: int, row: int, pid: int) -> int:
    b = f"{glyph_name}:{col},{row}:{pid}".encode("utf-8")
    return zlib.crc32(b) % PALETTE_SIZE


# -----------------------------
# Build & repack
# -----------------------------
def build_ttf(out_ttf: Path, glyph_mod) -> None:
    GLYPH_DATA = getattr(glyph_mod, "GLYPH_DATA", {})
    if not GLYPH_DATA:
        raise SystemExit("data/glyphs.py has no GLYPH_DATA")

    # Collect single-codepoint glyphs only (cmap-able)
    cmap: Dict[int, str] = {}
    base_tiles: Dict[str, List[Tile]] = {}

    for codepoint_key, rec in GLYPH_DATA.items():
        cps = rec.get("codepoints") or []
        if len(cps) != 1:
            continue  # ignore ligatures/multi-codepoint for now
        cp = int(cps[0])
        cp_hex = rec.get("codepoints_hex", [f"{cp:04x}"])[0]
        gname = _gname_from_codepoint_hex(cp_hex)

        tiles = _tiles_from_record(rec)
        if not tiles:
            continue

        cmap[cp] = gname
        base_tiles[gname] = tiles

    # Ensure space exists (even if not in glyph data)
    cmap.setdefault(0x20, "space")

    base_glyphs = [cmap[cp] for cp in sorted(k for k in cmap.keys() if k != 0x20)]
    primitives = [f"p{i}" for i in range(10)]
    mono_glyphs = [f"{g}.mono" for g in base_glyphs]

    glyph_order = [".notdef", "space"] + base_glyphs + mono_glyphs + primitives

    fb = FontBuilder(UPM, isTTF=True)
    fb.setupGlyphOrder(glyph_order)
    fb.setupCharacterMap(cmap)

    # Metrics (keep stable)
    hmtx = {g: (ADVANCE_WIDTH, 0) for g in glyph_order}
    hmtx["space"] = (ADVANCE_WIDTH, 0)
    for p in primitives:
        hmtx[p] = (CELL, 0)
    fb.setupHorizontalMetrics(hmtx)

    fb.setupHorizontalHeader(ascent=ASCENT, descent=-DESCENT)
    fb.setupOS2(
        sTypoAscender=ASCENT,
        sTypoDescender=-DESCENT,
        usWinAscent=ASCENT,
        usWinDescent=DESCENT,
    )
    fb.setupNameTable(
        {
            "familyName": FAMILY_NAME,
            "styleName": STYLE_NAME,
            "fullName": f"{FAMILY_NAME} {STYLE_NAME}",
            "uniqueFontIdentifier": f"{FAMILY_NAME}-{STYLE_NAME}",
            "psName": f"{FAMILY_NAME}-{STYLE_NAME}".replace(" ", ""),
        }
    )
    fb.setupPost()

    # glyf table
    glyf = {".notdef": build_notdef(), "space": TTGlyphPen(None).glyph()}

    for i in range(10):
        glyf[f"p{i}"] = build_primitive_glyph(i)

    primitive_glyphset = set(primitives)

    for gname in base_glyphs:
        tiles = base_tiles.get(gname, [])
        glyf[gname] = build_fallback_from_tiles(tiles)
        glyf[f"{gname}.mono"] = build_mono_composite_glyph(tiles, primitive_glyphset)

    fb.setupGlyf(glyf)

    # Fix LSB = xMin to avoid renderer-dependent shifts
    glyf_table = fb.font["glyf"]
    hmtx_table = fb.font["hmtx"]
    for gn in glyph_order:
        g = glyf_table[gn]
        g.recalcBounds(glyf_table)
        x_min = int(getattr(g, "xMin", 0) or 0)
        aw, _ = hmtx_table.metrics.get(gn, (ADVANCE_WIDTH, 0))
        hmtx_table.metrics[gn] = (int(aw), x_min)

    fb.setupMaxp()

    tt = fb.font

    # Palette (256 entries, stable)
    rng = random.Random(PALETTE_SEED)
    palette = [(rng.random(), rng.random(), rng.random(), 1.0) for _ in range(PALETTE_SIZE)]
    tt["CPAL"] = buildCPAL([palette])

    # COLR v1 mapping ONLY for base glyphs (mono glyphs intentionally omitted)
    colorGlyphs: Dict[str, dict] = {}
    for gname in base_glyphs:
        tiles = base_tiles.get(gname, [])
        layers: List[dict] = []

        for col, row, pid in tiles:
            dx = LEFT + col * CELL
            dy = TOP - (row + 1) * CELL
            pidx = palette_index_for(gname, col, row, pid)

            layers.append(
                {
                    "Format": ot.PaintFormat.PaintTransform,
                    "Paint": {
                        "Format": ot.PaintFormat.PaintGlyph,
                        "Glyph": f"p{pid}",
                        "Paint": {
                            "Format": ot.PaintFormat.PaintSolid,
                            "PaletteIndex": pidx,
                            "Alpha": 1.0,
                        },
                    },
                    "Transform": {
                        "xx": 1.0,
                        "yx": 0.0,
                        "xy": 0.0,
                        "yy": 1.0,
                        "dx": dx,
                        "dy": dy,
                    },
                }
            )

        colorGlyphs[gname] = {
            "Format": ot.PaintFormat.PaintColrLayers,
            "Layers": layers,
        }

    tt["COLR"] = buildCOLR(colorGlyphs, version=1, glyphMap=tt.getReverseGlyphMap())

    # GSUB: ss01 swaps base glyphs to their monochrome alternates
    fea = ["feature ss01 {"]
    for gname in base_glyphs:
        fea.append(f"  sub {gname} by {gname}.mono;")
    fea.append("} ss01;")
    addOpenTypeFeaturesFromString(tt, "\n".join(fea))

    tt.save(out_ttf)


def repack_web_fonts(out_ttf: Path, out_woff: Path, out_woff2: Path) -> None:
    # WOFF
    tt = TTFont(str(out_ttf))
    tt.flavor = "woff"
    tt.save(str(out_woff))

    # WOFF2 (may require brotli; catch and report nicely)
    try:
        tt = TTFont(str(out_ttf))
        tt.flavor = "woff2"
        tt.save(str(out_woff2))
    except Exception as e:
        print(f"NOTE: Could not write WOFF2 ({out_woff2.name}): {e}")
        print("      Install with: pip install brotli")


def copy_stylesheet(root_dir: Path, out_dir: Path) -> None:
    src = root_dir / "src" / "style" / "main.css"
    dst = out_dir / "primitives.css"
    if not src.exists():
        print(f"NOTE: stylesheet not found, skipping: {src}")
        return
    dst.write_text(src.read_text(encoding="utf-8"), encoding="utf-8")
    print(f"Wrote: {dst}")


def main() -> None:
    script_dir = Path(__file__).resolve().parent
    root_dir = script_dir.parent
    out_dir = root_dir / "dist" / "fonts"
    out_dir.mkdir(parents=True, exist_ok=True)

    glyph_mod = _load_glyphs_module(root_dir)

    out_ttf = out_dir / f"{OUT_BASENAME}.ttf"
    out_woff = out_dir / f"{OUT_BASENAME}.woff"
    out_woff2 = out_dir / f"{OUT_BASENAME}.woff2"

    build_ttf(out_ttf, glyph_mod)
    print(f"Wrote: {out_ttf}")

    repack_web_fonts(out_ttf, out_woff, out_woff2)
    print(f"Wrote: {out_woff}")
    if out_woff2.exists():
        print(f"Wrote: {out_woff2}")

    copy_stylesheet(root_dir, out_dir)


if __name__ == "__main__":
    main()